import = ["~/.config/alacritty/kanagawa.toml"]

[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[shell]
program = "/usr/bin/zsh"
# args = ["-c", "tmux"]

[font]
normal.family = "JetbrainsMono Nerd Font"
size = 11.5

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Command"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"


[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "none"
dynamic_padding = true
opacity = 0.75


[window.dimensions]
columns = 100
lines = 85

[window.padding]
x = 0
y = 0
